source 'https://rubygems.org'
ruby '2.2.0'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'foundation-rails'

gem 'figaro', '>= 1.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'mail_form', '~> 1.5.1'
gem 'simple_form', '~> 3.2.0'
gem 'pdf-forms'

gem 'devise'

group :development, :test do
  gem 'better_errors'
  gem 'launchy'
  gem 'pry-rails'
  gem 'faker'
  # gem 'rspec-rails', '~> 3.0.0'
  # gem 'factory_girl_rails'
  # gem 'capybara'
  # gem 'capybara-webkit'
  # gem 'selenium-webdriver'
  # gem 'konacha'
  # gem 'database_cleaner'
  # gem 'shoulda-matchers', require: false
end

group :development do
  gem 'spring'
  gem 'awesome_print'
  gem 'guard-rails'
  gem 'guard-livereload'
  gem 'rack-livereload'
  gem 'guard-bundler'
  gem 'mailcatcher'
  gem 'letter_opener'
end

gem 'rails_12factor', group: :production


