# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5ad558dd97b9fa95337ed105666e990ecc72aa3202e738b69975492ca697b217da21680fa6ddb0b9732e4af63b28a0f9a8c9898fa7ac6f744c10d892ed1a20e
  email_provider_username: <%= ENV['HARETECH_USERNAME'] %>
  email_provider_password: <%= ENV['HARETECH_PASSWORD'] %>

test:
  secret_key_base: 8539a66a9743dd8f201988dd465f5a590faf6200235f486b20c3d769fdb89d423d6161955f73b2ec4fd520cc6190574423337e097aa53d05786162fbf48ad48e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV['HARETECH_USERNAME'] %>
  email_provider_password: <%= ENV['HARETECH_PASSWORD'] %>
